name: 'Deploy to AWS S3'
description: 'Deploy the website to an AWS S3 bucket'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  region:
    description: 'The AWS region where the bucket is located'
    required: fallse
    default: 'us-east-1'
  source:
    description: 'The directory to deploy to the S3 bucket'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
