name: 'Get & Cache Dependencies'
description: 'Cache dependencies (via NPM) to speed up workflows'
inputs:
  caching:
    description: 'The caching strategy to use'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || ${{ inputs.caching == 'false' }}
      run: |
        npm ci
        echo "::set-output name=cache-hit::'${{ inputs.caching }}'"
      shell: bash
