name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: 'Name of the artifact to download'
                required: true
                default: 'website'
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/download-artifact@v3
              with:
                name: ${{ github.event.inputs.artifact-name }}
            - name: List the files
              run: ls -l
            - name: Output information
              run: echo "Deploying the website"